import React, { useState, useContext, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import '../styles/home.css';
import { AuthContext } from '../authContext';

export default function JoinRoomPage() {
  const { user, token, logout } = useContext(AuthContext); 
  const navigate = useNavigate();

  const [joinRoomId, setJoinRoomId] = useState('');
  const [joinPassword, setJoinPassword] = useState('');
  const [projectNameCreate, setProjectNameCreate] = useState('');
  const [customRoomId, setCustomRoomId] = useState('');
  const [autoGeneratedId, setAutoGeneratedId] = useState('');
  const [scheduledRooms, setScheduledRooms] = useState([]);
  const [recentActivity, setRecentActivity] = useState([]);

  const [showScheduleForm, setShowScheduleForm] = useState(false);
  const [scheduleProjectName, setScheduleProjectName] = useState('');
  const [scheduleDateTime, setScheduleDateTime] = useState('');

  const [showMenu, setShowMenu] = useState(false);

  const avatarLetter =
    user?.name?.[0]?.toUpperCase() ||
    user?.email?.[0]?.toUpperCase() ||
    'U';

  const authHeader = {
    headers: { Authorization: `Bearer ${token}` },
  };

  useEffect(() => {
    if (!token) return;

    const load = async () => {
      try {
        const [schedRes, recentRes] = await Promise.all([
          axios.get('http://localhost:5000/api/rooms/scheduled', authHeader),
          axios.get('http://localhost:5000/api/rooms/recent', authHeader),
        ]);
        setScheduledRooms(schedRes.data || []);
        setRecentActivity((recentRes.data || []).slice(0, 6));
      } catch (e) {
        console.error('LOAD DASHBOARD ERROR', e);
      }
    };

    load();
  }, [token]);

  const handleCreateClick = async () => {
    if (!projectNameCreate.trim()) return;

    try {
      const body = {
        projectName: projectNameCreate.trim(),
        customRoomId: customRoomId.trim() || undefined,
      };
      const res = await axios.post(
        'http://localhost:5000/api/rooms/create',
        body,
        authHeader
      );

      const { roomId, projectName } = res.data;

      const recentRes = await axios.get(
        'http://localhost:5000/api/rooms/recent',
        authHeader
      );
      setRecentActivity((recentRes.data || []).slice(0, 6));

      navigate(`/room/${roomId}`, { state: { projectName } });
    } catch (e) {
      console.error('CREATE ROOM ERROR', e);
    }
  };

  const handleJoinClick = () => {
    if (!joinRoomId.trim()) return;
    navigate(`/room/${joinRoomId.trim()}`, {
      state: { projectName: 'Untitled Project', joinPassword },
    });
  };

  const handleScheduleRoom = async () => {
    if (!scheduleProjectName.trim() || !scheduleDateTime) return;

    try {
      const res = await axios.post(
        'http://localhost:5000/api/rooms/schedule',
        {
          projectName: scheduleProjectName.trim(),
          scheduledAt: scheduleDateTime, 
        },
        authHeader
      );
      setScheduledRooms((prev) => [...prev, res.data]);
      setShowScheduleForm(false);
      setScheduleProjectName('');
      setScheduleDateTime('');
    } catch (e) {
      console.error('SCHEDULE ROOM ERROR', e);
    }
  };

  const handleGenerateId = () => {
    const id = Math.random().toString(36).substring(2, 8);
    setAutoGeneratedId(id);
    setCustomRoomId(id);
  };

  const canJoinScheduled = (scheduledAt) =>
    new Date(scheduledAt).getTime() <= Date.now();

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('user');

    if (logout) {
      logout(); 
    }

    navigate('/login', { replace: true });
  };

  return (
    <div className="jr-root">
      <div className="jr-main">
        <header className="jr-topbar">
          <div className="jr-topbar-left">
           <div className="jr-logo">
          <span className="jr-logo-mark">◼</span>
          <span className="jr-logo-text">code-collab</span>
        </div>
          </div>

          <div className="jr-topbar-right" style={{ position: 'relative' }}>
            <div
              className="jr-profile-circle"
              onClick={() => setShowMenu((prev) => !prev)}
              style={{ cursor: 'pointer' }}
            >
              {avatarLetter}
            </div>

            {showMenu && (
              <div className="jr-profile-menu">
                <button className="jr-logout-btn" onClick={handleLogout}>
                  Logout
                </button>
              </div>
            )}
          </div>
        </header>

        <main className="jr-content">
          {/* PROFILE CARD */}
          <section className="jr-profile-card">
            <div className="jr-profile-avatar">{avatarLetter}</div>
            <div className="jr-profile-info">
              <div className="jr-profile-name">
                {user?.name || 'User'}
              </div>
              <div className="jr-profile-plan">
                Plan: <span>Code‑Collab Basic</span>
              </div>
            </div>
            <div className="jr-profile-actions">
              <button className="jr-outline-btn">Manage Plan</button>
              <button className="jr-link-btn">View Plan Details</button>
            </div>
          </section>

          <section className="jr-card-row">
            <div className="jr-card jr-card-wide">
              <h2 className="jr-card-title">Schedule a room</h2>
              <p className="jr-card-text">
                Plan a collaborative coding session for later and share
                the room details with your team.
              </p>
              <button
                className="jr-primary-btn"
                onClick={() => setShowScheduleForm(true)}
              >
                Schedule Room
              </button>

              {showScheduleForm && (
                <div className="jr-schedule-form">
                  <div className="jr-form-group">
                    <label className="jr-label">Project name</label>
                    <input
                      className="jr-input"
                      value={scheduleProjectName}
                      onChange={(e) =>
                        setScheduleProjectName(e.target.value)
                      }
                      placeholder="Project name"
                    />
                  </div>
                  <div className="jr-form-group">
                    <label className="jr-label">Date & time</label>
                    <input
                      className="jr-input"
                      type="datetime-local"
                      value={scheduleDateTime}
                      onChange={(e) =>
                        setScheduleDateTime(e.target.value)
                      }
                    />
                  </div>
                  <div className="jr-form-inline">
                    <button
                      className="jr-secondary-btn"
                      type="button"
                      onClick={() => setShowScheduleForm(false)}
                    >
                      Cancel
                    </button>
                    <button
                      className="jr-primary-btn"
                      type="button"
                      onClick={handleScheduleRoom}
                    >
                      Save schedule
                    </button>
                  </div>
                </div>
              )}
            </div>

            <div className="jr-card jr-card-meetings">
              <div className="jr-meetings-header">
                <span className="jr-meetings-title">Scheduled Rooms</span>
                <button className="jr-link-btn jr-meetings-link">
                  View Rooms
                </button>
              </div>

              {scheduledRooms.length === 0 ? (
                <>
                  <div className="jr-meetings-empty">
                    No upcoming scheduled rooms
                  </div>
                  <button
                    className="jr-outline-btn jr-meetings-test-btn"
                    onClick={() => setShowScheduleForm(true)}
                  >
                    Schedule a Room
                  </button>
                </>
              ) : (
                <>
                  <div className="jr-meetings-list">
                    {scheduledRooms.map((room) => {
                      const canJoin = canJoinScheduled(room.scheduledAt);
                      return (
                        <div
                          key={room._id}
                          className="jr-meeting-item"
                        >
                          <div className="jr-meeting-title">
                            {room.projectName}
                          </div>
                          <div className="jr-meeting-time">
                            {new Date(
                              room.scheduledAt
                            ).toLocaleString()}
                          </div>
                          <button
                            type="button"
                            disabled={!canJoin}
                            className={
                              canJoin
                                ? 'jr-primary-btn jr-meeting-join-btn'
                                : 'jr-disabled-btn jr-meeting-join-btn'
                            }
                            onClick={() =>
                              canJoin &&
                              navigate(`/room/${room.roomId}`, {
                                state: { projectName: room.projectName },
                              })
                            }
                          >
                            Join Room
                          </button>
                        </div>
                      );
                    })}
                  </div>
                  <button className="jr-outline-btn jr-meetings-test-btn">
                    Test Audio and Video
                  </button>
                </>
              )}
            </div>
          </section>

          <section className="jr-card-row">
            <div className="jr-card jr-card-half">
              <h3 className="jr-card-title">Join a room</h3>
              <p className="jr-card-text">
                Enter a room ID and password shared by someone else.
              </p>
              <div className="jr-form-group">
                <label className="jr-label">Room ID</label>
                <input
                  className="jr-input"
                  type="text"
                  placeholder="Enter room ID"
                  value={joinRoomId}
                  onChange={(e) => setJoinRoomId(e.target.value)}
                />
              </div>
              <div className="jr-form-group">
                <label className="jr-label">Room password</label>
                <input
                  className="jr-input"
                  type="password"
                  placeholder="Enter room password"
                  value={joinPassword}
                  onChange={(e) => setJoinPassword(e.target.value)}
                />
              </div>
              <button
                className="jr-primary-btn"
                onClick={handleJoinClick}
              >
                Join Room
              </button>
            </div>

            <div className="jr-card jr-card-half">
              <h3 className="jr-card-title">Create a room</h3>
              <p className="jr-card-text">
                Set a project name and optional custom room ID to start
                coding instantly.
              </p>
              <div className="jr-form-group">
                <label className="jr-label">Project name</label>
                <input
                  className="jr-input"
                  type="text"
                  placeholder="Project name"
                  value={projectNameCreate}
                  onChange={(e) =>
                    setProjectNameCreate(e.target.value)
                  }
                />
              </div>
              <div className="jr-form-group">
                <label className="jr-label">
                  Custom room ID (optional)
                </label>
                <input
                  className="jr-input"
                  type="text"
                  placeholder="Set your own room ID"
                  value={customRoomId}
                  onChange={(e) => setCustomRoomId(e.target.value)}
                />
              </div>
              <div className="jr-form-inline">
                <button
                  className="jr-secondary-btn"
                  onClick={handleGenerateId}
                >
                  Generate ID
                </button>
                {autoGeneratedId && (
                  <span className="jr-generated-id">
                    Generated: <strong>{autoGeneratedId}</strong>
                  </span>
                )}
              </div>
              <button
                className="jr-primary-btn"
                onClick={handleCreateClick}
              >
                Create Room
              </button>
            </div>
          </section>

          <section className="jr-card-row">
            <div className="jr-card jr-card-wide">
              <h3 className="jr-card-title">Recent activity</h3>
              {recentActivity.length === 0 ? (
                <div className="jr-meetings-empty">
                  No recent activity yet
                </div>
              ) : (
                <div className="jr-activity-list">
                  {recentActivity.slice(0, 6).map((item, idx) => (
                    <div key={idx} className="jr-activity-item">
                      <div className="jr-activity-room">
                        Project: <strong>{item.projectName}</strong>
                      </div>
                      <div className="jr-activity-room">
                        Room ID: <strong>{item.roomId}</strong>
                      </div>
                      <div className="jr-activity-time">
                        Joined:{' '}
                        {new Date(item.joinedAt).toLocaleString()}
                      </div>
                      {item.files && item.files.length > 0 && (
                        <div className="jr-activity-files">
                          Files: {item.files.join(', ')}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </section>
        </main>
      </div>
    </div>
  );
}
